//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО__Стройматериалы_.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ArticleNumber { get; set; }
        public int NameProductID { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> MAXdiscount { get; set; }
        public int ManufacturerAndProviderID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> CountInStock { get; set; }
        public string Description { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual ManufacturerAndProviderProduct ManufacturerAndProviderProduct { get; set; }
        public virtual NameProduct NameProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
